apiVersion: v1
kind: Service
metadata:
  name: knative-kafka-channel-controller
  namespace: knative-eventing
  labels:
    helm.sh/chart: knative-kafka
    k8s-app: knative-kafka-channel-controller
spec:
  selector:
    app: knative-kafka-channel-controller
  ports:
  - name: metrics
    protocol: TCP
    port: 8081
    targetPort: 8081
---